services:
  app:
    container_name: ai-tech-service-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID:-}
        NEXT_PUBLIC_CLARITY_ID: ${NEXT_PUBLIC_CLARITY_ID:-}
    environment:
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD:-}
    ports:
      - "8999:80"
    restart: unless-stopped
    networks:
      - apps-network

networks:
  apps-network:
    external: true
